In [6]:
import numpy as np

In [7]:
km = np.loadtxt('../data/carros-km.txt', dtype=int)
anos = np.loadtxt('../data/carros-anos.txt', dtype=int)

In [8]:
km_media = km / (2022 - anos)

In [9]:
ano_atual, ano_fab, km_total = 2022, 2003, 444410.0
km_media = km_total / (ano_atual - ano_fab)
km_media

23390.0

In [10]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
dados = [
  ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Banco de couro','Ar condicionado','Sensor de estacionamento','Sensor crepuscular', 'Sensor de chuva'],
  ['Central multimídia', 'Teto panorâmico','Freios ABS','4 x 4','Painel digital','Piloto automático','Bancos de couro','Câmera de estacionamento'],
  ['Piloto automático','Controle de estabilidade','Sensor crepuscular','Freios ABS','Câmbio automático', 'Bancos de couro','Central multimídia','Vidros elétricos']
]
dados

[['Rodas de liga',
  'Travas elétricas',
  'Piloto automático',
  'Banco de couro',
  'Ar condicionado',
  'Sensor de estacionamento',
  'Sensor crepuscular',
  'Sensor de chuva'],
 ['Central multimídia',
  'Teto panorâmico',
  'Freios ABS',
  '4 x 4',
  'Painel digital',
  'Piloto automático',
  'Bancos de couro',
  'Câmera de estacionamento'],
 ['Piloto automático',
  'Controle de estabilidade',
  'Sensor crepuscular',
  'Freios ABS',
  'Câmbio automático',
  'Bancos de couro',
  'Central multimídia',
  'Vidros elétricos']]

In [20]:
acessorios = np.array(dados)
acessorios.shape

(3, 8)

In [21]:
np_array = np.arange(1000000)
py_list = list(range(1000000))

In [23]:
# analise de performance
%time for _ in range(100): np_array *= 2

CPU times: total: 93.8 ms
Wall time: 72.8 ms


In [24]:
# analise de performance
%time for _ in range(100): py_list = [x * 2 for x in py_list]

CPU times: total: 9.98 s
Wall time: 10.1 s


In [25]:
km = np.array([44410., 5712, 37123, 0., 25757.])
anos = np.array([2003, 1991, 1990, 2019, 2006])
idade = 2019 - anos # operação não permitida se não fosse numpy array
idade

array([16, 28, 29,  0, 13])

In [28]:
dados = np.array([km, anos])
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [30]:
contador = np.arange(10)

In [31]:
dados.shape

(2, 5)

In [32]:
dados.ndim

2

In [33]:
dados.size

10

In [34]:
dados.dtype

dtype('float64')

In [35]:
dados.T

array([[44410.,  2003.],
       [ 5712.,  1991.],
       [37123.,  1990.],
       [    0.,  2019.],
       [25757.,  2006.]])

In [37]:
dados.transpose()

array([[44410.,  2003.],
       [ 5712.,  1991.],
       [37123.,  1990.],
       [    0.,  2019.],
       [25757.,  2006.]])

In [38]:
dados.tolist()

[[44410.0, 5712.0, 37123.0, 0.0, 25757.0],
 [2003.0, 1991.0, 1990.0, 2019.0, 2006.0]]

In [39]:
contador.reshape((5,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [41]:
contador.reshape((5,2), order='F')

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [42]:
contador.reshape((5,2), order='C')

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [48]:
n = [2003, 1991, 1990, 2019, 2006]
n2 = [44410., 5712, 37123, 0., 25757.]
n3 = n + n2

n4 = np.array(n3).reshape((5,2), order='F')
n4

array([[ 2003., 44410.],
       [ 1991.,  5712.],
       [ 1990., 37123.],
       [ 2019.,     0.],
       [ 2006., 25757.]])

In [56]:
dados_copy = dados.copy()
dados_copy.resize((3, 5), refcheck=False)
dados_copy[2] = dados_copy[0] / (2022 - dados_copy[1])
dados_copy

array([[44410.        ,  5712.        , 37123.        ,     0.        ,
        25757.        ],
       [ 2003.        ,  1991.        ,  1990.        ,  2019.        ,
         2006.        ],
       [ 2337.36842105,   184.25806452,  1160.09375   ,     0.        ,
         1609.8125    ]])

In [57]:
km = np.loadtxt('../data/carros-km.txt', dtype=int)
anos = np.loadtxt('../data/carros-anos.txt', dtype=int)
valor = np.loadtxt('../data/carros-valor.txt')

In [59]:
dataset = np.column_stack((anos, km, valor))
dataset.shape

(258, 3)

In [65]:
np.mean(dataset[:,2], axis=0)

98960.51310077519

In [64]:
np.std(dataset[:, 2], axis=0)

29754.101150388564

In [67]:
dataset.sum(axis=0)

array([  517938.        , 11480849.        , 25531812.37999999])

In [68]:
dataset[:, 1].sum()

11480849.0

In [70]:
np.sum(dataset[:, 1], axis=0)

11480849.0